from homeassistant.components.water_heater import (
    SUPPORT_OPERATION_MODE,
    SUPPORT_TARGET_TEMPERATURE
)

GE_CCM = SUPPORT_OPERATION_MODE | SUPPORT_TARGET_TEMPERATURE
MAX_CUPS = 10
MIN_CUPS = 2